package com.dankegongyu.bi.valuation.dw_temp.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class BiRoomPriceExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bi_room_price
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bi_room_price
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bi_room_price
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bi_room_price
     *
     * @mbggenerated
     */
    public BiRoomPriceExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bi_room_price
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bi_room_price
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bi_room_price
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bi_room_price
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bi_room_price
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bi_room_price
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bi_room_price
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bi_room_price
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bi_room_price
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bi_room_price
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bi_room_price
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCityIsNull() {
            addCriterion("city is null");
            return (Criteria) this;
        }

        public Criteria andCityIsNotNull() {
            addCriterion("city is not null");
            return (Criteria) this;
        }

        public Criteria andCityEqualTo(String value) {
            addCriterion("city =", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotEqualTo(String value) {
            addCriterion("city <>", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThan(String value) {
            addCriterion("city >", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThanOrEqualTo(String value) {
            addCriterion("city >=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThan(String value) {
            addCriterion("city <", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThanOrEqualTo(String value) {
            addCriterion("city <=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLike(String value) {
            addCriterion("city like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotLike(String value) {
            addCriterion("city not like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityIn(List<String> values) {
            addCriterion("city in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotIn(List<String> values) {
            addCriterion("city not in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityBetween(String value1, String value2) {
            addCriterion("city between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotBetween(String value1, String value2) {
            addCriterion("city not between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andBlockIsNull() {
            addCriterion("block is null");
            return (Criteria) this;
        }

        public Criteria andBlockIsNotNull() {
            addCriterion("block is not null");
            return (Criteria) this;
        }

        public Criteria andBlockEqualTo(String value) {
            addCriterion("block =", value, "block");
            return (Criteria) this;
        }

        public Criteria andBlockNotEqualTo(String value) {
            addCriterion("block <>", value, "block");
            return (Criteria) this;
        }

        public Criteria andBlockGreaterThan(String value) {
            addCriterion("block >", value, "block");
            return (Criteria) this;
        }

        public Criteria andBlockGreaterThanOrEqualTo(String value) {
            addCriterion("block >=", value, "block");
            return (Criteria) this;
        }

        public Criteria andBlockLessThan(String value) {
            addCriterion("block <", value, "block");
            return (Criteria) this;
        }

        public Criteria andBlockLessThanOrEqualTo(String value) {
            addCriterion("block <=", value, "block");
            return (Criteria) this;
        }

        public Criteria andBlockLike(String value) {
            addCriterion("block like", value, "block");
            return (Criteria) this;
        }

        public Criteria andBlockNotLike(String value) {
            addCriterion("block not like", value, "block");
            return (Criteria) this;
        }

        public Criteria andBlockIn(List<String> values) {
            addCriterion("block in", values, "block");
            return (Criteria) this;
        }

        public Criteria andBlockNotIn(List<String> values) {
            addCriterion("block not in", values, "block");
            return (Criteria) this;
        }

        public Criteria andBlockBetween(String value1, String value2) {
            addCriterion("block between", value1, value2, "block");
            return (Criteria) this;
        }

        public Criteria andBlockNotBetween(String value1, String value2) {
            addCriterion("block not between", value1, value2, "block");
            return (Criteria) this;
        }

        public Criteria andCommunityIsNull() {
            addCriterion("community is null");
            return (Criteria) this;
        }

        public Criteria andCommunityIsNotNull() {
            addCriterion("community is not null");
            return (Criteria) this;
        }

        public Criteria andCommunityEqualTo(String value) {
            addCriterion("community =", value, "community");
            return (Criteria) this;
        }

        public Criteria andCommunityNotEqualTo(String value) {
            addCriterion("community <>", value, "community");
            return (Criteria) this;
        }

        public Criteria andCommunityGreaterThan(String value) {
            addCriterion("community >", value, "community");
            return (Criteria) this;
        }

        public Criteria andCommunityGreaterThanOrEqualTo(String value) {
            addCriterion("community >=", value, "community");
            return (Criteria) this;
        }

        public Criteria andCommunityLessThan(String value) {
            addCriterion("community <", value, "community");
            return (Criteria) this;
        }

        public Criteria andCommunityLessThanOrEqualTo(String value) {
            addCriterion("community <=", value, "community");
            return (Criteria) this;
        }

        public Criteria andCommunityLike(String value) {
            addCriterion("community like", value, "community");
            return (Criteria) this;
        }

        public Criteria andCommunityNotLike(String value) {
            addCriterion("community not like", value, "community");
            return (Criteria) this;
        }

        public Criteria andCommunityIn(List<String> values) {
            addCriterion("community in", values, "community");
            return (Criteria) this;
        }

        public Criteria andCommunityNotIn(List<String> values) {
            addCriterion("community not in", values, "community");
            return (Criteria) this;
        }

        public Criteria andCommunityBetween(String value1, String value2) {
            addCriterion("community between", value1, value2, "community");
            return (Criteria) this;
        }

        public Criteria andCommunityNotBetween(String value1, String value2) {
            addCriterion("community not between", value1, value2, "community");
            return (Criteria) this;
        }

        public Criteria andSuiteIdIsNull() {
            addCriterion("suite_id is null");
            return (Criteria) this;
        }

        public Criteria andSuiteIdIsNotNull() {
            addCriterion("suite_id is not null");
            return (Criteria) this;
        }

        public Criteria andSuiteIdEqualTo(Integer value) {
            addCriterion("suite_id =", value, "suiteId");
            return (Criteria) this;
        }

        public Criteria andSuiteIdNotEqualTo(Integer value) {
            addCriterion("suite_id <>", value, "suiteId");
            return (Criteria) this;
        }

        public Criteria andSuiteIdGreaterThan(Integer value) {
            addCriterion("suite_id >", value, "suiteId");
            return (Criteria) this;
        }

        public Criteria andSuiteIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("suite_id >=", value, "suiteId");
            return (Criteria) this;
        }

        public Criteria andSuiteIdLessThan(Integer value) {
            addCriterion("suite_id <", value, "suiteId");
            return (Criteria) this;
        }

        public Criteria andSuiteIdLessThanOrEqualTo(Integer value) {
            addCriterion("suite_id <=", value, "suiteId");
            return (Criteria) this;
        }

        public Criteria andSuiteIdIn(List<Integer> values) {
            addCriterion("suite_id in", values, "suiteId");
            return (Criteria) this;
        }

        public Criteria andSuiteIdNotIn(List<Integer> values) {
            addCriterion("suite_id not in", values, "suiteId");
            return (Criteria) this;
        }

        public Criteria andSuiteIdBetween(Integer value1, Integer value2) {
            addCriterion("suite_id between", value1, value2, "suiteId");
            return (Criteria) this;
        }

        public Criteria andSuiteIdNotBetween(Integer value1, Integer value2) {
            addCriterion("suite_id not between", value1, value2, "suiteId");
            return (Criteria) this;
        }

        public Criteria andCodeIsNull() {
            addCriterion("code is null");
            return (Criteria) this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("code is not null");
            return (Criteria) this;
        }

        public Criteria andCodeEqualTo(String value) {
            addCriterion("code =", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotEqualTo(String value) {
            addCriterion("code <>", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThan(String value) {
            addCriterion("code >", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(String value) {
            addCriterion("code >=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThan(String value) {
            addCriterion("code <", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThanOrEqualTo(String value) {
            addCriterion("code <=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLike(String value) {
            addCriterion("code like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotLike(String value) {
            addCriterion("code not like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeIn(List<String> values) {
            addCriterion("code in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotIn(List<String> values) {
            addCriterion("code not in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeBetween(String value1, String value2) {
            addCriterion("code between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotBetween(String value1, String value2) {
            addCriterion("code not between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andRoomPriceIsNull() {
            addCriterion("room_price is null");
            return (Criteria) this;
        }

        public Criteria andRoomPriceIsNotNull() {
            addCriterion("room_price is not null");
            return (Criteria) this;
        }

        public Criteria andRoomPriceEqualTo(Integer value) {
            addCriterion("room_price =", value, "roomPrice");
            return (Criteria) this;
        }

        public Criteria andRoomPriceNotEqualTo(Integer value) {
            addCriterion("room_price <>", value, "roomPrice");
            return (Criteria) this;
        }

        public Criteria andRoomPriceGreaterThan(Integer value) {
            addCriterion("room_price >", value, "roomPrice");
            return (Criteria) this;
        }

        public Criteria andRoomPriceGreaterThanOrEqualTo(Integer value) {
            addCriterion("room_price >=", value, "roomPrice");
            return (Criteria) this;
        }

        public Criteria andRoomPriceLessThan(Integer value) {
            addCriterion("room_price <", value, "roomPrice");
            return (Criteria) this;
        }

        public Criteria andRoomPriceLessThanOrEqualTo(Integer value) {
            addCriterion("room_price <=", value, "roomPrice");
            return (Criteria) this;
        }

        public Criteria andRoomPriceIn(List<Integer> values) {
            addCriterion("room_price in", values, "roomPrice");
            return (Criteria) this;
        }

        public Criteria andRoomPriceNotIn(List<Integer> values) {
            addCriterion("room_price not in", values, "roomPrice");
            return (Criteria) this;
        }

        public Criteria andRoomPriceBetween(Integer value1, Integer value2) {
            addCriterion("room_price between", value1, value2, "roomPrice");
            return (Criteria) this;
        }

        public Criteria andRoomPriceNotBetween(Integer value1, Integer value2) {
            addCriterion("room_price not between", value1, value2, "roomPrice");
            return (Criteria) this;
        }

        public Criteria andAdjRoomOutpricePreIsNull() {
            addCriterion("adj_room_outprice_pre is null");
            return (Criteria) this;
        }

        public Criteria andAdjRoomOutpricePreIsNotNull() {
            addCriterion("adj_room_outprice_pre is not null");
            return (Criteria) this;
        }

        public Criteria andAdjRoomOutpricePreEqualTo(Integer value) {
            addCriterion("adj_room_outprice_pre =", value, "adjRoomOutpricePre");
            return (Criteria) this;
        }

        public Criteria andAdjRoomOutpricePreNotEqualTo(Integer value) {
            addCriterion("adj_room_outprice_pre <>", value, "adjRoomOutpricePre");
            return (Criteria) this;
        }

        public Criteria andAdjRoomOutpricePreGreaterThan(Integer value) {
            addCriterion("adj_room_outprice_pre >", value, "adjRoomOutpricePre");
            return (Criteria) this;
        }

        public Criteria andAdjRoomOutpricePreGreaterThanOrEqualTo(Integer value) {
            addCriterion("adj_room_outprice_pre >=", value, "adjRoomOutpricePre");
            return (Criteria) this;
        }

        public Criteria andAdjRoomOutpricePreLessThan(Integer value) {
            addCriterion("adj_room_outprice_pre <", value, "adjRoomOutpricePre");
            return (Criteria) this;
        }

        public Criteria andAdjRoomOutpricePreLessThanOrEqualTo(Integer value) {
            addCriterion("adj_room_outprice_pre <=", value, "adjRoomOutpricePre");
            return (Criteria) this;
        }

        public Criteria andAdjRoomOutpricePreIn(List<Integer> values) {
            addCriterion("adj_room_outprice_pre in", values, "adjRoomOutpricePre");
            return (Criteria) this;
        }

        public Criteria andAdjRoomOutpricePreNotIn(List<Integer> values) {
            addCriterion("adj_room_outprice_pre not in", values, "adjRoomOutpricePre");
            return (Criteria) this;
        }

        public Criteria andAdjRoomOutpricePreBetween(Integer value1, Integer value2) {
            addCriterion("adj_room_outprice_pre between", value1, value2, "adjRoomOutpricePre");
            return (Criteria) this;
        }

        public Criteria andAdjRoomOutpricePreNotBetween(Integer value1, Integer value2) {
            addCriterion("adj_room_outprice_pre not between", value1, value2, "adjRoomOutpricePre");
            return (Criteria) this;
        }

        public Criteria andRoomPriceFinalIsNull() {
            addCriterion("room_price_final is null");
            return (Criteria) this;
        }

        public Criteria andRoomPriceFinalIsNotNull() {
            addCriterion("room_price_final is not null");
            return (Criteria) this;
        }

        public Criteria andRoomPriceFinalEqualTo(Integer value) {
            addCriterion("room_price_final =", value, "roomPriceFinal");
            return (Criteria) this;
        }

        public Criteria andRoomPriceFinalNotEqualTo(Integer value) {
            addCriterion("room_price_final <>", value, "roomPriceFinal");
            return (Criteria) this;
        }

        public Criteria andRoomPriceFinalGreaterThan(Integer value) {
            addCriterion("room_price_final >", value, "roomPriceFinal");
            return (Criteria) this;
        }

        public Criteria andRoomPriceFinalGreaterThanOrEqualTo(Integer value) {
            addCriterion("room_price_final >=", value, "roomPriceFinal");
            return (Criteria) this;
        }

        public Criteria andRoomPriceFinalLessThan(Integer value) {
            addCriterion("room_price_final <", value, "roomPriceFinal");
            return (Criteria) this;
        }

        public Criteria andRoomPriceFinalLessThanOrEqualTo(Integer value) {
            addCriterion("room_price_final <=", value, "roomPriceFinal");
            return (Criteria) this;
        }

        public Criteria andRoomPriceFinalIn(List<Integer> values) {
            addCriterion("room_price_final in", values, "roomPriceFinal");
            return (Criteria) this;
        }

        public Criteria andRoomPriceFinalNotIn(List<Integer> values) {
            addCriterion("room_price_final not in", values, "roomPriceFinal");
            return (Criteria) this;
        }

        public Criteria andRoomPriceFinalBetween(Integer value1, Integer value2) {
            addCriterion("room_price_final between", value1, value2, "roomPriceFinal");
            return (Criteria) this;
        }

        public Criteria andRoomPriceFinalNotBetween(Integer value1, Integer value2) {
            addCriterion("room_price_final not between", value1, value2, "roomPriceFinal");
            return (Criteria) this;
        }

        public Criteria andXiaoquStdPriceIsNull() {
            addCriterion("xiaoqu_std_price is null");
            return (Criteria) this;
        }

        public Criteria andXiaoquStdPriceIsNotNull() {
            addCriterion("xiaoqu_std_price is not null");
            return (Criteria) this;
        }

        public Criteria andXiaoquStdPriceEqualTo(Integer value) {
            addCriterion("xiaoqu_std_price =", value, "xiaoquStdPrice");
            return (Criteria) this;
        }

        public Criteria andXiaoquStdPriceNotEqualTo(Integer value) {
            addCriterion("xiaoqu_std_price <>", value, "xiaoquStdPrice");
            return (Criteria) this;
        }

        public Criteria andXiaoquStdPriceGreaterThan(Integer value) {
            addCriterion("xiaoqu_std_price >", value, "xiaoquStdPrice");
            return (Criteria) this;
        }

        public Criteria andXiaoquStdPriceGreaterThanOrEqualTo(Integer value) {
            addCriterion("xiaoqu_std_price >=", value, "xiaoquStdPrice");
            return (Criteria) this;
        }

        public Criteria andXiaoquStdPriceLessThan(Integer value) {
            addCriterion("xiaoqu_std_price <", value, "xiaoquStdPrice");
            return (Criteria) this;
        }

        public Criteria andXiaoquStdPriceLessThanOrEqualTo(Integer value) {
            addCriterion("xiaoqu_std_price <=", value, "xiaoquStdPrice");
            return (Criteria) this;
        }

        public Criteria andXiaoquStdPriceIn(List<Integer> values) {
            addCriterion("xiaoqu_std_price in", values, "xiaoquStdPrice");
            return (Criteria) this;
        }

        public Criteria andXiaoquStdPriceNotIn(List<Integer> values) {
            addCriterion("xiaoqu_std_price not in", values, "xiaoquStdPrice");
            return (Criteria) this;
        }

        public Criteria andXiaoquStdPriceBetween(Integer value1, Integer value2) {
            addCriterion("xiaoqu_std_price between", value1, value2, "xiaoquStdPrice");
            return (Criteria) this;
        }

        public Criteria andXiaoquStdPriceNotBetween(Integer value1, Integer value2) {
            addCriterion("xiaoqu_std_price not between", value1, value2, "xiaoquStdPrice");
            return (Criteria) this;
        }

        public Criteria andBlockStdPriceIsNull() {
            addCriterion("block_std_price is null");
            return (Criteria) this;
        }

        public Criteria andBlockStdPriceIsNotNull() {
            addCriterion("block_std_price is not null");
            return (Criteria) this;
        }

        public Criteria andBlockStdPriceEqualTo(Integer value) {
            addCriterion("block_std_price =", value, "blockStdPrice");
            return (Criteria) this;
        }

        public Criteria andBlockStdPriceNotEqualTo(Integer value) {
            addCriterion("block_std_price <>", value, "blockStdPrice");
            return (Criteria) this;
        }

        public Criteria andBlockStdPriceGreaterThan(Integer value) {
            addCriterion("block_std_price >", value, "blockStdPrice");
            return (Criteria) this;
        }

        public Criteria andBlockStdPriceGreaterThanOrEqualTo(Integer value) {
            addCriterion("block_std_price >=", value, "blockStdPrice");
            return (Criteria) this;
        }

        public Criteria andBlockStdPriceLessThan(Integer value) {
            addCriterion("block_std_price <", value, "blockStdPrice");
            return (Criteria) this;
        }

        public Criteria andBlockStdPriceLessThanOrEqualTo(Integer value) {
            addCriterion("block_std_price <=", value, "blockStdPrice");
            return (Criteria) this;
        }

        public Criteria andBlockStdPriceIn(List<Integer> values) {
            addCriterion("block_std_price in", values, "blockStdPrice");
            return (Criteria) this;
        }

        public Criteria andBlockStdPriceNotIn(List<Integer> values) {
            addCriterion("block_std_price not in", values, "blockStdPrice");
            return (Criteria) this;
        }

        public Criteria andBlockStdPriceBetween(Integer value1, Integer value2) {
            addCriterion("block_std_price between", value1, value2, "blockStdPrice");
            return (Criteria) this;
        }

        public Criteria andBlockStdPriceNotBetween(Integer value1, Integer value2) {
            addCriterion("block_std_price not between", value1, value2, "blockStdPrice");
            return (Criteria) this;
        }

        public Criteria andPriceLabelIsNull() {
            addCriterion("price_label is null");
            return (Criteria) this;
        }

        public Criteria andPriceLabelIsNotNull() {
            addCriterion("price_label is not null");
            return (Criteria) this;
        }

        public Criteria andPriceLabelEqualTo(String value) {
            addCriterion("price_label =", value, "priceLabel");
            return (Criteria) this;
        }

        public Criteria andPriceLabelNotEqualTo(String value) {
            addCriterion("price_label <>", value, "priceLabel");
            return (Criteria) this;
        }

        public Criteria andPriceLabelGreaterThan(String value) {
            addCriterion("price_label >", value, "priceLabel");
            return (Criteria) this;
        }

        public Criteria andPriceLabelGreaterThanOrEqualTo(String value) {
            addCriterion("price_label >=", value, "priceLabel");
            return (Criteria) this;
        }

        public Criteria andPriceLabelLessThan(String value) {
            addCriterion("price_label <", value, "priceLabel");
            return (Criteria) this;
        }

        public Criteria andPriceLabelLessThanOrEqualTo(String value) {
            addCriterion("price_label <=", value, "priceLabel");
            return (Criteria) this;
        }

        public Criteria andPriceLabelLike(String value) {
            addCriterion("price_label like", value, "priceLabel");
            return (Criteria) this;
        }

        public Criteria andPriceLabelNotLike(String value) {
            addCriterion("price_label not like", value, "priceLabel");
            return (Criteria) this;
        }

        public Criteria andPriceLabelIn(List<String> values) {
            addCriterion("price_label in", values, "priceLabel");
            return (Criteria) this;
        }

        public Criteria andPriceLabelNotIn(List<String> values) {
            addCriterion("price_label not in", values, "priceLabel");
            return (Criteria) this;
        }

        public Criteria andPriceLabelBetween(String value1, String value2) {
            addCriterion("price_label between", value1, value2, "priceLabel");
            return (Criteria) this;
        }

        public Criteria andPriceLabelNotBetween(String value1, String value2) {
            addCriterion("price_label not between", value1, value2, "priceLabel");
            return (Criteria) this;
        }

        public Criteria andXiaoquStdPriceTypeIsNull() {
            addCriterion("xiaoqu_std_price_type is null");
            return (Criteria) this;
        }

        public Criteria andXiaoquStdPriceTypeIsNotNull() {
            addCriterion("xiaoqu_std_price_type is not null");
            return (Criteria) this;
        }

        public Criteria andXiaoquStdPriceTypeEqualTo(String value) {
            addCriterion("xiaoqu_std_price_type =", value, "xiaoquStdPriceType");
            return (Criteria) this;
        }

        public Criteria andXiaoquStdPriceTypeNotEqualTo(String value) {
            addCriterion("xiaoqu_std_price_type <>", value, "xiaoquStdPriceType");
            return (Criteria) this;
        }

        public Criteria andXiaoquStdPriceTypeGreaterThan(String value) {
            addCriterion("xiaoqu_std_price_type >", value, "xiaoquStdPriceType");
            return (Criteria) this;
        }

        public Criteria andXiaoquStdPriceTypeGreaterThanOrEqualTo(String value) {
            addCriterion("xiaoqu_std_price_type >=", value, "xiaoquStdPriceType");
            return (Criteria) this;
        }

        public Criteria andXiaoquStdPriceTypeLessThan(String value) {
            addCriterion("xiaoqu_std_price_type <", value, "xiaoquStdPriceType");
            return (Criteria) this;
        }

        public Criteria andXiaoquStdPriceTypeLessThanOrEqualTo(String value) {
            addCriterion("xiaoqu_std_price_type <=", value, "xiaoquStdPriceType");
            return (Criteria) this;
        }

        public Criteria andXiaoquStdPriceTypeLike(String value) {
            addCriterion("xiaoqu_std_price_type like", value, "xiaoquStdPriceType");
            return (Criteria) this;
        }

        public Criteria andXiaoquStdPriceTypeNotLike(String value) {
            addCriterion("xiaoqu_std_price_type not like", value, "xiaoquStdPriceType");
            return (Criteria) this;
        }

        public Criteria andXiaoquStdPriceTypeIn(List<String> values) {
            addCriterion("xiaoqu_std_price_type in", values, "xiaoquStdPriceType");
            return (Criteria) this;
        }

        public Criteria andXiaoquStdPriceTypeNotIn(List<String> values) {
            addCriterion("xiaoqu_std_price_type not in", values, "xiaoquStdPriceType");
            return (Criteria) this;
        }

        public Criteria andXiaoquStdPriceTypeBetween(String value1, String value2) {
            addCriterion("xiaoqu_std_price_type between", value1, value2, "xiaoquStdPriceType");
            return (Criteria) this;
        }

        public Criteria andXiaoquStdPriceTypeNotBetween(String value1, String value2) {
            addCriterion("xiaoqu_std_price_type not between", value1, value2, "xiaoquStdPriceType");
            return (Criteria) this;
        }

        public Criteria andRentTypeIsNull() {
            addCriterion("rent_type is null");
            return (Criteria) this;
        }

        public Criteria andRentTypeIsNotNull() {
            addCriterion("rent_type is not null");
            return (Criteria) this;
        }

        public Criteria andRentTypeEqualTo(String value) {
            addCriterion("rent_type =", value, "rentType");
            return (Criteria) this;
        }

        public Criteria andRentTypeNotEqualTo(String value) {
            addCriterion("rent_type <>", value, "rentType");
            return (Criteria) this;
        }

        public Criteria andRentTypeGreaterThan(String value) {
            addCriterion("rent_type >", value, "rentType");
            return (Criteria) this;
        }

        public Criteria andRentTypeGreaterThanOrEqualTo(String value) {
            addCriterion("rent_type >=", value, "rentType");
            return (Criteria) this;
        }

        public Criteria andRentTypeLessThan(String value) {
            addCriterion("rent_type <", value, "rentType");
            return (Criteria) this;
        }

        public Criteria andRentTypeLessThanOrEqualTo(String value) {
            addCriterion("rent_type <=", value, "rentType");
            return (Criteria) this;
        }

        public Criteria andRentTypeLike(String value) {
            addCriterion("rent_type like", value, "rentType");
            return (Criteria) this;
        }

        public Criteria andRentTypeNotLike(String value) {
            addCriterion("rent_type not like", value, "rentType");
            return (Criteria) this;
        }

        public Criteria andRentTypeIn(List<String> values) {
            addCriterion("rent_type in", values, "rentType");
            return (Criteria) this;
        }

        public Criteria andRentTypeNotIn(List<String> values) {
            addCriterion("rent_type not in", values, "rentType");
            return (Criteria) this;
        }

        public Criteria andRentTypeBetween(String value1, String value2) {
            addCriterion("rent_type between", value1, value2, "rentType");
            return (Criteria) this;
        }

        public Criteria andRentTypeNotBetween(String value1, String value2) {
            addCriterion("rent_type not between", value1, value2, "rentType");
            return (Criteria) this;
        }

        public Criteria andPdateIsNull() {
            addCriterion("pdate is null");
            return (Criteria) this;
        }

        public Criteria andPdateIsNotNull() {
            addCriterion("pdate is not null");
            return (Criteria) this;
        }

        public Criteria andPdateEqualTo(Date value) {
            addCriterionForJDBCDate("pdate =", value, "pdate");
            return (Criteria) this;
        }

        public Criteria andPdateNotEqualTo(Date value) {
            addCriterionForJDBCDate("pdate <>", value, "pdate");
            return (Criteria) this;
        }

        public Criteria andPdateGreaterThan(Date value) {
            addCriterionForJDBCDate("pdate >", value, "pdate");
            return (Criteria) this;
        }

        public Criteria andPdateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("pdate >=", value, "pdate");
            return (Criteria) this;
        }

        public Criteria andPdateLessThan(Date value) {
            addCriterionForJDBCDate("pdate <", value, "pdate");
            return (Criteria) this;
        }

        public Criteria andPdateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("pdate <=", value, "pdate");
            return (Criteria) this;
        }

        public Criteria andPdateIn(List<Date> values) {
            addCriterionForJDBCDate("pdate in", values, "pdate");
            return (Criteria) this;
        }

        public Criteria andPdateNotIn(List<Date> values) {
            addCriterionForJDBCDate("pdate not in", values, "pdate");
            return (Criteria) this;
        }

        public Criteria andPdateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("pdate between", value1, value2, "pdate");
            return (Criteria) this;
        }

        public Criteria andPdateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("pdate not between", value1, value2, "pdate");
            return (Criteria) this;
        }

        public Criteria andIsAbnormalIsNull() {
            addCriterion("is_abnormal is null");
            return (Criteria) this;
        }

        public Criteria andIsAbnormalIsNotNull() {
            addCriterion("is_abnormal is not null");
            return (Criteria) this;
        }

        public Criteria andIsAbnormalEqualTo(Integer value) {
            addCriterion("is_abnormal =", value, "isAbnormal");
            return (Criteria) this;
        }

        public Criteria andIsAbnormalNotEqualTo(Integer value) {
            addCriterion("is_abnormal <>", value, "isAbnormal");
            return (Criteria) this;
        }

        public Criteria andIsAbnormalGreaterThan(Integer value) {
            addCriterion("is_abnormal >", value, "isAbnormal");
            return (Criteria) this;
        }

        public Criteria andIsAbnormalGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_abnormal >=", value, "isAbnormal");
            return (Criteria) this;
        }

        public Criteria andIsAbnormalLessThan(Integer value) {
            addCriterion("is_abnormal <", value, "isAbnormal");
            return (Criteria) this;
        }

        public Criteria andIsAbnormalLessThanOrEqualTo(Integer value) {
            addCriterion("is_abnormal <=", value, "isAbnormal");
            return (Criteria) this;
        }

        public Criteria andIsAbnormalIn(List<Integer> values) {
            addCriterion("is_abnormal in", values, "isAbnormal");
            return (Criteria) this;
        }

        public Criteria andIsAbnormalNotIn(List<Integer> values) {
            addCriterion("is_abnormal not in", values, "isAbnormal");
            return (Criteria) this;
        }

        public Criteria andIsAbnormalBetween(Integer value1, Integer value2) {
            addCriterion("is_abnormal between", value1, value2, "isAbnormal");
            return (Criteria) this;
        }

        public Criteria andIsAbnormalNotBetween(Integer value1, Integer value2) {
            addCriterion("is_abnormal not between", value1, value2, "isAbnormal");
            return (Criteria) this;
        }

        public Criteria andIsFirstIsNull() {
            addCriterion("is_first is null");
            return (Criteria) this;
        }

        public Criteria andIsFirstIsNotNull() {
            addCriterion("is_first is not null");
            return (Criteria) this;
        }

        public Criteria andIsFirstEqualTo(Integer value) {
            addCriterion("is_first =", value, "isFirst");
            return (Criteria) this;
        }

        public Criteria andIsFirstNotEqualTo(Integer value) {
            addCriterion("is_first <>", value, "isFirst");
            return (Criteria) this;
        }

        public Criteria andIsFirstGreaterThan(Integer value) {
            addCriterion("is_first >", value, "isFirst");
            return (Criteria) this;
        }

        public Criteria andIsFirstGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_first >=", value, "isFirst");
            return (Criteria) this;
        }

        public Criteria andIsFirstLessThan(Integer value) {
            addCriterion("is_first <", value, "isFirst");
            return (Criteria) this;
        }

        public Criteria andIsFirstLessThanOrEqualTo(Integer value) {
            addCriterion("is_first <=", value, "isFirst");
            return (Criteria) this;
        }

        public Criteria andIsFirstIn(List<Integer> values) {
            addCriterion("is_first in", values, "isFirst");
            return (Criteria) this;
        }

        public Criteria andIsFirstNotIn(List<Integer> values) {
            addCriterion("is_first not in", values, "isFirst");
            return (Criteria) this;
        }

        public Criteria andIsFirstBetween(Integer value1, Integer value2) {
            addCriterion("is_first between", value1, value2, "isFirst");
            return (Criteria) this;
        }

        public Criteria andIsFirstNotBetween(Integer value1, Integer value2) {
            addCriterion("is_first not between", value1, value2, "isFirst");
            return (Criteria) this;
        }

        public Criteria andIsSyncIsNull() {
            addCriterion("is_sync is null");
            return (Criteria) this;
        }

        public Criteria andIsSyncIsNotNull() {
            addCriterion("is_sync is not null");
            return (Criteria) this;
        }

        public Criteria andIsSyncEqualTo(Integer value) {
            addCriterion("is_sync =", value, "isSync");
            return (Criteria) this;
        }

        public Criteria andIsSyncNotEqualTo(Integer value) {
            addCriterion("is_sync <>", value, "isSync");
            return (Criteria) this;
        }

        public Criteria andIsSyncGreaterThan(Integer value) {
            addCriterion("is_sync >", value, "isSync");
            return (Criteria) this;
        }

        public Criteria andIsSyncGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_sync >=", value, "isSync");
            return (Criteria) this;
        }

        public Criteria andIsSyncLessThan(Integer value) {
            addCriterion("is_sync <", value, "isSync");
            return (Criteria) this;
        }

        public Criteria andIsSyncLessThanOrEqualTo(Integer value) {
            addCriterion("is_sync <=", value, "isSync");
            return (Criteria) this;
        }

        public Criteria andIsSyncIn(List<Integer> values) {
            addCriterion("is_sync in", values, "isSync");
            return (Criteria) this;
        }

        public Criteria andIsSyncNotIn(List<Integer> values) {
            addCriterion("is_sync not in", values, "isSync");
            return (Criteria) this;
        }

        public Criteria andIsSyncBetween(Integer value1, Integer value2) {
            addCriterion("is_sync between", value1, value2, "isSync");
            return (Criteria) this;
        }

        public Criteria andIsSyncNotBetween(Integer value1, Integer value2) {
            addCriterion("is_sync not between", value1, value2, "isSync");
            return (Criteria) this;
        }

        public Criteria andProcessStatusIsNull() {
            addCriterion("process_status is null");
            return (Criteria) this;
        }

        public Criteria andProcessStatusIsNotNull() {
            addCriterion("process_status is not null");
            return (Criteria) this;
        }

        public Criteria andProcessStatusEqualTo(Integer value) {
            addCriterion("process_status =", value, "processStatus");
            return (Criteria) this;
        }

        public Criteria andProcessStatusNotEqualTo(Integer value) {
            addCriterion("process_status <>", value, "processStatus");
            return (Criteria) this;
        }

        public Criteria andProcessStatusGreaterThan(Integer value) {
            addCriterion("process_status >", value, "processStatus");
            return (Criteria) this;
        }

        public Criteria andProcessStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("process_status >=", value, "processStatus");
            return (Criteria) this;
        }

        public Criteria andProcessStatusLessThan(Integer value) {
            addCriterion("process_status <", value, "processStatus");
            return (Criteria) this;
        }

        public Criteria andProcessStatusLessThanOrEqualTo(Integer value) {
            addCriterion("process_status <=", value, "processStatus");
            return (Criteria) this;
        }

        public Criteria andProcessStatusIn(List<Integer> values) {
            addCriterion("process_status in", values, "processStatus");
            return (Criteria) this;
        }

        public Criteria andProcessStatusNotIn(List<Integer> values) {
            addCriterion("process_status not in", values, "processStatus");
            return (Criteria) this;
        }

        public Criteria andProcessStatusBetween(Integer value1, Integer value2) {
            addCriterion("process_status between", value1, value2, "processStatus");
            return (Criteria) this;
        }

        public Criteria andProcessStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("process_status not between", value1, value2, "processStatus");
            return (Criteria) this;
        }

        public Criteria andSyncRemarkIsNull() {
            addCriterion("sync_remark is null");
            return (Criteria) this;
        }

        public Criteria andSyncRemarkIsNotNull() {
            addCriterion("sync_remark is not null");
            return (Criteria) this;
        }

        public Criteria andSyncRemarkEqualTo(String value) {
            addCriterion("sync_remark =", value, "syncRemark");
            return (Criteria) this;
        }

        public Criteria andSyncRemarkNotEqualTo(String value) {
            addCriterion("sync_remark <>", value, "syncRemark");
            return (Criteria) this;
        }

        public Criteria andSyncRemarkGreaterThan(String value) {
            addCriterion("sync_remark >", value, "syncRemark");
            return (Criteria) this;
        }

        public Criteria andSyncRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("sync_remark >=", value, "syncRemark");
            return (Criteria) this;
        }

        public Criteria andSyncRemarkLessThan(String value) {
            addCriterion("sync_remark <", value, "syncRemark");
            return (Criteria) this;
        }

        public Criteria andSyncRemarkLessThanOrEqualTo(String value) {
            addCriterion("sync_remark <=", value, "syncRemark");
            return (Criteria) this;
        }

        public Criteria andSyncRemarkLike(String value) {
            addCriterion("sync_remark like", value, "syncRemark");
            return (Criteria) this;
        }

        public Criteria andSyncRemarkNotLike(String value) {
            addCriterion("sync_remark not like", value, "syncRemark");
            return (Criteria) this;
        }

        public Criteria andSyncRemarkIn(List<String> values) {
            addCriterion("sync_remark in", values, "syncRemark");
            return (Criteria) this;
        }

        public Criteria andSyncRemarkNotIn(List<String> values) {
            addCriterion("sync_remark not in", values, "syncRemark");
            return (Criteria) this;
        }

        public Criteria andSyncRemarkBetween(String value1, String value2) {
            addCriterion("sync_remark between", value1, value2, "syncRemark");
            return (Criteria) this;
        }

        public Criteria andSyncRemarkNotBetween(String value1, String value2) {
            addCriterion("sync_remark not between", value1, value2, "syncRemark");
            return (Criteria) this;
        }

        public Criteria andSpreadIsNull() {
            addCriterion("spread is null");
            return (Criteria) this;
        }

        public Criteria andSpreadIsNotNull() {
            addCriterion("spread is not null");
            return (Criteria) this;
        }

        public Criteria andSpreadEqualTo(String value) {
            addCriterion("spread =", value, "spread");
            return (Criteria) this;
        }

        public Criteria andSpreadNotEqualTo(String value) {
            addCriterion("spread <>", value, "spread");
            return (Criteria) this;
        }

        public Criteria andSpreadGreaterThan(String value) {
            addCriterion("spread >", value, "spread");
            return (Criteria) this;
        }

        public Criteria andSpreadGreaterThanOrEqualTo(String value) {
            addCriterion("spread >=", value, "spread");
            return (Criteria) this;
        }

        public Criteria andSpreadLessThan(String value) {
            addCriterion("spread <", value, "spread");
            return (Criteria) this;
        }

        public Criteria andSpreadLessThanOrEqualTo(String value) {
            addCriterion("spread <=", value, "spread");
            return (Criteria) this;
        }

        public Criteria andSpreadLike(String value) {
            addCriterion("spread like", value, "spread");
            return (Criteria) this;
        }

        public Criteria andSpreadNotLike(String value) {
            addCriterion("spread not like", value, "spread");
            return (Criteria) this;
        }

        public Criteria andSpreadIn(List<String> values) {
            addCriterion("spread in", values, "spread");
            return (Criteria) this;
        }

        public Criteria andSpreadNotIn(List<String> values) {
            addCriterion("spread not in", values, "spread");
            return (Criteria) this;
        }

        public Criteria andSpreadBetween(String value1, String value2) {
            addCriterion("spread between", value1, value2, "spread");
            return (Criteria) this;
        }

        public Criteria andSpreadNotBetween(String value1, String value2) {
            addCriterion("spread not between", value1, value2, "spread");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bi_room_price
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bi_room_price
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}