package com.dankegongyu.bi.valuation.dw_temp.model;

import java.util.Date;

public class BiRoomPrice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bi_room_price.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bi_room_price.city
     *
     * @mbggenerated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bi_room_price.block
     *
     * @mbggenerated
     */
    private String block;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bi_room_price.community
     *
     * @mbggenerated
     */
    private String community;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bi_room_price.suite_id
     *
     * @mbggenerated
     */
    private Integer suiteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bi_room_price.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bi_room_price.room_price
     *
     * @mbggenerated
     */
    private Integer roomPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bi_room_price.adj_room_outprice_pre
     *
     * @mbggenerated
     */
    private Integer adjRoomOutpricePre;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bi_room_price.room_price_final
     *
     * @mbggenerated
     */
    private Integer roomPriceFinal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bi_room_price.xiaoqu_std_price
     *
     * @mbggenerated
     */
    private Integer xiaoquStdPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bi_room_price.block_std_price
     *
     * @mbggenerated
     */
    private Integer blockStdPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bi_room_price.price_label
     *
     * @mbggenerated
     */
    private String priceLabel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bi_room_price.xiaoqu_std_price_type
     *
     * @mbggenerated
     */
    private String xiaoquStdPriceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bi_room_price.rent_type
     *
     * @mbggenerated
     */
    private String rentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bi_room_price.pdate
     *
     * @mbggenerated
     */
    private Date pdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bi_room_price.is_abnormal
     *
     * @mbggenerated
     */
    private Integer isAbnormal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bi_room_price.is_first
     *
     * @mbggenerated
     */
    private Integer isFirst;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bi_room_price.is_sync
     *
     * @mbggenerated
     */
    private Integer isSync;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bi_room_price.process_status
     *
     * @mbggenerated
     */
    private Integer processStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bi_room_price.sync_remark
     *
     * @mbggenerated
     */
    private String syncRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bi_room_price.spread
     *
     * @mbggenerated
     */
    private String spread;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bi_room_price.id
     *
     * @return the value of bi_room_price.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bi_room_price.id
     *
     * @param id the value for bi_room_price.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bi_room_price.city
     *
     * @return the value of bi_room_price.city
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bi_room_price.city
     *
     * @param city the value for bi_room_price.city
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bi_room_price.block
     *
     * @return the value of bi_room_price.block
     *
     * @mbggenerated
     */
    public String getBlock() {
        return block;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bi_room_price.block
     *
     * @param block the value for bi_room_price.block
     *
     * @mbggenerated
     */
    public void setBlock(String block) {
        this.block = block == null ? null : block.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bi_room_price.community
     *
     * @return the value of bi_room_price.community
     *
     * @mbggenerated
     */
    public String getCommunity() {
        return community;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bi_room_price.community
     *
     * @param community the value for bi_room_price.community
     *
     * @mbggenerated
     */
    public void setCommunity(String community) {
        this.community = community == null ? null : community.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bi_room_price.suite_id
     *
     * @return the value of bi_room_price.suite_id
     *
     * @mbggenerated
     */
    public Integer getSuiteId() {
        return suiteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bi_room_price.suite_id
     *
     * @param suiteId the value for bi_room_price.suite_id
     *
     * @mbggenerated
     */
    public void setSuiteId(Integer suiteId) {
        this.suiteId = suiteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bi_room_price.code
     *
     * @return the value of bi_room_price.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bi_room_price.code
     *
     * @param code the value for bi_room_price.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bi_room_price.room_price
     *
     * @return the value of bi_room_price.room_price
     *
     * @mbggenerated
     */
    public Integer getRoomPrice() {
        return roomPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bi_room_price.room_price
     *
     * @param roomPrice the value for bi_room_price.room_price
     *
     * @mbggenerated
     */
    public void setRoomPrice(Integer roomPrice) {
        this.roomPrice = roomPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bi_room_price.adj_room_outprice_pre
     *
     * @return the value of bi_room_price.adj_room_outprice_pre
     *
     * @mbggenerated
     */
    public Integer getAdjRoomOutpricePre() {
        return adjRoomOutpricePre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bi_room_price.adj_room_outprice_pre
     *
     * @param adjRoomOutpricePre the value for bi_room_price.adj_room_outprice_pre
     *
     * @mbggenerated
     */
    public void setAdjRoomOutpricePre(Integer adjRoomOutpricePre) {
        this.adjRoomOutpricePre = adjRoomOutpricePre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bi_room_price.room_price_final
     *
     * @return the value of bi_room_price.room_price_final
     *
     * @mbggenerated
     */
    public Integer getRoomPriceFinal() {
        return roomPriceFinal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bi_room_price.room_price_final
     *
     * @param roomPriceFinal the value for bi_room_price.room_price_final
     *
     * @mbggenerated
     */
    public void setRoomPriceFinal(Integer roomPriceFinal) {
        this.roomPriceFinal = roomPriceFinal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bi_room_price.xiaoqu_std_price
     *
     * @return the value of bi_room_price.xiaoqu_std_price
     *
     * @mbggenerated
     */
    public Integer getXiaoquStdPrice() {
        return xiaoquStdPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bi_room_price.xiaoqu_std_price
     *
     * @param xiaoquStdPrice the value for bi_room_price.xiaoqu_std_price
     *
     * @mbggenerated
     */
    public void setXiaoquStdPrice(Integer xiaoquStdPrice) {
        this.xiaoquStdPrice = xiaoquStdPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bi_room_price.block_std_price
     *
     * @return the value of bi_room_price.block_std_price
     *
     * @mbggenerated
     */
    public Integer getBlockStdPrice() {
        return blockStdPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bi_room_price.block_std_price
     *
     * @param blockStdPrice the value for bi_room_price.block_std_price
     *
     * @mbggenerated
     */
    public void setBlockStdPrice(Integer blockStdPrice) {
        this.blockStdPrice = blockStdPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bi_room_price.price_label
     *
     * @return the value of bi_room_price.price_label
     *
     * @mbggenerated
     */
    public String getPriceLabel() {
        return priceLabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bi_room_price.price_label
     *
     * @param priceLabel the value for bi_room_price.price_label
     *
     * @mbggenerated
     */
    public void setPriceLabel(String priceLabel) {
        this.priceLabel = priceLabel == null ? null : priceLabel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bi_room_price.xiaoqu_std_price_type
     *
     * @return the value of bi_room_price.xiaoqu_std_price_type
     *
     * @mbggenerated
     */
    public String getXiaoquStdPriceType() {
        return xiaoquStdPriceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bi_room_price.xiaoqu_std_price_type
     *
     * @param xiaoquStdPriceType the value for bi_room_price.xiaoqu_std_price_type
     *
     * @mbggenerated
     */
    public void setXiaoquStdPriceType(String xiaoquStdPriceType) {
        this.xiaoquStdPriceType = xiaoquStdPriceType == null ? null : xiaoquStdPriceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bi_room_price.rent_type
     *
     * @return the value of bi_room_price.rent_type
     *
     * @mbggenerated
     */
    public String getRentType() {
        return rentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bi_room_price.rent_type
     *
     * @param rentType the value for bi_room_price.rent_type
     *
     * @mbggenerated
     */
    public void setRentType(String rentType) {
        this.rentType = rentType == null ? null : rentType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bi_room_price.pdate
     *
     * @return the value of bi_room_price.pdate
     *
     * @mbggenerated
     */
    public Date getPdate() {
        return pdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bi_room_price.pdate
     *
     * @param pdate the value for bi_room_price.pdate
     *
     * @mbggenerated
     */
    public void setPdate(Date pdate) {
        this.pdate = pdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bi_room_price.is_abnormal
     *
     * @return the value of bi_room_price.is_abnormal
     *
     * @mbggenerated
     */
    public Integer getIsAbnormal() {
        return isAbnormal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bi_room_price.is_abnormal
     *
     * @param isAbnormal the value for bi_room_price.is_abnormal
     *
     * @mbggenerated
     */
    public void setIsAbnormal(Integer isAbnormal) {
        this.isAbnormal = isAbnormal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bi_room_price.is_first
     *
     * @return the value of bi_room_price.is_first
     *
     * @mbggenerated
     */
    public Integer getIsFirst() {
        return isFirst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bi_room_price.is_first
     *
     * @param isFirst the value for bi_room_price.is_first
     *
     * @mbggenerated
     */
    public void setIsFirst(Integer isFirst) {
        this.isFirst = isFirst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bi_room_price.is_sync
     *
     * @return the value of bi_room_price.is_sync
     *
     * @mbggenerated
     */
    public Integer getIsSync() {
        return isSync;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bi_room_price.is_sync
     *
     * @param isSync the value for bi_room_price.is_sync
     *
     * @mbggenerated
     */
    public void setIsSync(Integer isSync) {
        this.isSync = isSync;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bi_room_price.process_status
     *
     * @return the value of bi_room_price.process_status
     *
     * @mbggenerated
     */
    public Integer getProcessStatus() {
        return processStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bi_room_price.process_status
     *
     * @param processStatus the value for bi_room_price.process_status
     *
     * @mbggenerated
     */
    public void setProcessStatus(Integer processStatus) {
        this.processStatus = processStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bi_room_price.sync_remark
     *
     * @return the value of bi_room_price.sync_remark
     *
     * @mbggenerated
     */
    public String getSyncRemark() {
        return syncRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bi_room_price.sync_remark
     *
     * @param syncRemark the value for bi_room_price.sync_remark
     *
     * @mbggenerated
     */
    public void setSyncRemark(String syncRemark) {
        this.syncRemark = syncRemark == null ? null : syncRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bi_room_price.spread
     *
     * @return the value of bi_room_price.spread
     *
     * @mbggenerated
     */
    public String getSpread() {
        return spread;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bi_room_price.spread
     *
     * @param spread the value for bi_room_price.spread
     *
     * @mbggenerated
     */
    public void setSpread(String spread) {
        this.spread = spread == null ? null : spread.trim();
    }
}